"""Transfer the Engineering Decision Notebook from reports/edn.md into LaTeX.

reports/edn.md is where an EDN entry is written and the only place it is ever
edited (AGENTS.md). This module transfers the entries into reports/latex/edn/,
one `\\ednentry` file per entry, which edn.tex builds into
MLOps_Recommenditos_EDN.pdf. With some seventy entries, most of them with nested
alternatives, links and amendment notes, a transfer by hand would be the slowest
step of a delivery and the one most likely to drift from the source. The
transfer is idempotent: run twice on the same notebook it rewrites nothing, and
run after an edit it changes the files of exactly the entries that changed.

The rule it serves is that the LaTeX is never behind the notebook: whoever
changes reports/edn.md runs `make edn` in the same pull request. `check` changes
nothing and reports what a transfer would change; the required Tests job runs it
as a test on every change to the notebook or its LaTeX, which blocks the merge,
and CI's report job runs it as `--check`. So an entry's **In LaTeX: yes**, which
only the transfer writes, means that the entry is in the PDF exactly as the
notebook states it.

It needs nothing beyond the standard library, so that CI can run the check
without the project environment.

What a run does, in order:

* parses the `## Entries` section of reports/edn.md into entries and fields,
  failing with the entry and the line named when a required field is missing,
  a field appears twice or a line belongs to no field, because a transfer that
  drops text quietly is worse than none;
* renders the Markdown each field holds - the subset the notebook uses, which
  is paragraphs, nested bullet lists, pipe tables, block quotes, and inline
  code, bold, italics, links and autolinks - and refuses what it would not
  render faithfully, such as a fenced code block or a character pdfLaTeX cannot
  typeset, so the failure names the entry instead of a TeX log line;
* writes one file per entry as `edn/NN-slug.tex` and the `\\input` list as
  `edn/entries.tex`, and deletes a generated entry file that no entry produces
  any more (a renamed title changes the slug);
* sets every transferred entry's **In LaTeX** field to `yes` in reports/edn.md,
  adding the field where an entry lacks it, and changes nothing else there.

How the Markdown fields map onto the course's, since the two are not the same:

* The course has no slot for alternatives, so, as reports/latex/README.md says,
  they go into the rationale: first the alternatives with their pros and cons,
  because the rationale argues in terms of them, then the rationale itself.
* A block quote above an entry's fields is how the notebook records that a later
  entry amended this one or that its evidence was corrected. It becomes the
  entry's `note`, which edn.tex prints first, so a reader of the PDF sees that an
  entry was revised before reading what it decided.
* A field the template does not define (EDN-59 has one) is appended to the field
  above it under its own label, so nothing in the source is dropped.
* A field that holds only "-" is the template's "does not apply" and is left out.
* `In LaTeX` is bookkeeping and is not rendered.
* A link to another entry becomes a link inside the PDF, and a relative link to a
  file of the repository becomes its URL on GitHub's `main`, because the PDF is
  read outside the checkout.

An entry whose heading has no fields yet is an ID reserved on `main` before the
branch that needs it was opened (reports/edn.md, "How to add an entry"). It is
skipped with a warning rather than treated as an error, and transferred by the
first run after it has been written.
"""

import argparse
from dataclasses import dataclass, field
from pathlib import Path
import posixpath
import re
import sys
import unicodedata

# Derived from this file's location, like tools/requirement_matrix.py does: the
# notebook and the LaTeX are files of the checkout the tool runs in.
PROJ_ROOT = Path(__file__).resolve().parents[1]
EDN_MD = PROJ_ROOT / "reports" / "edn.md"
LATEX_EDN_DIR = PROJ_ROOT / "reports" / "latex" / "edn"
ENTRY_LIST_NAME = "entries.tex"

#: Where relative links of the notebook point once they leave the checkout.
REPO_URL = "https://github.com/mlops-2627q1-mds-upc/MLOPS_Recommenditos"
#: The notebook's own location in the repository, which relative links start from.
EDN_MD_REPO_DIR = "reports"

#: The first line of every file this module writes. It is what marks a file as
#: generated, so that a stale one may be deleted and a hand-written one never is.
GENERATED_MARKER = "% Generated by tools/edn_latex.py from reports/edn.md."
DO_NOT_EDIT = "% Do not edit: change reports/edn.md and run `make edn`."

#: The Markdown labels of the notebook's template and the `\ednentry` keys they
#: become. `alternatives` has no key of its own and is rendered into `rationale`,
#: and `in_latex` is bookkeeping.
FIELD_KEYS = {
    "Date": "date",
    "Milestone": "milestone",
    "Activity / Topic": "topic",
    "Participants": "participants",
    "Decision": "decision",
    "Alternatives considered": "alternatives",
    "Rationale": "rationale",
    "AI involvement": "ai",
    "Response to AI": "response",
    "Assessment of the AI contribution": "assessment",
    "AI interaction evidence": "aievidence",
    "Other evidence": "evidence",
    "In LaTeX": "in_latex",
}
IN_LATEX_LABEL = "In LaTeX"

#: The fields edn.tex refuses to build without, checked here as well so that the
#: error names the entry in reports/edn.md rather than in a TeX log.
REQUIRED_FIELDS = ("milestone", "participants", "decision", "rationale", "ai")

#: The order of the keys in a generated file, which is the order edn.tex prints.
OUTPUT_KEYS = (
    "id",
    "title",
    "note",
    "date",
    "milestone",
    "topic",
    "participants",
    "decision",
    "rationale",
    "ai",
    "response",
    "assessment",
    "aievidence",
    "evidence",
)

ENTRIES_HEADING = "## Entries"
#: How a fenced code block opens, which the notebook's entries may not use: the
#: renderer has no verbatim block, and it would typeset the code as prose.
FENCES = ("```", "~~~")
ENTRY_HEADING = re.compile(r"^### (EDN-(\d+)): (.+?)\s*$")
FIELD_LINE = re.compile(r"^- \*\*(?P<label>[^*]+?):\*\*(?: (?P<rest>.*))?$")
EDN_ANCHOR = re.compile(r"^#edn-(\d+)\b")
AUTOLINK = re.compile(r"<(https?://[^>\s]+)>")
#: Characters that may appear in a URL as written; anything else is refused
#: rather than passed to `\href`, where it could break the build.
URL_SAFE = re.compile(r"^[A-Za-z0-9\-._~:/?#\[\]@!$&'()*+,;=%]+$")

#: How many spaces a nested block is indented by in the notebook.
INDENT = 2
#: A pipe table is a header row and a delimiter row at least.
TABLE_MIN_ROWS = 2
#: Below this a character is ASCII, and below the next one Latin-1, which is
#: what inputenc typesets without help.
ASCII_END = 0x80
LATIN1_END = 0x100

#: Non-ASCII characters the notebook may use, and what pdfLaTeX gets instead.
#: Latin-1 letters such as `ä` are typeset by inputenc as they are; anything not
#: listed and not a Latin-1 letter is refused (see `_check_characters`).
UNICODE_TO_LATEX = {
    "§": r"\S{}",
    "±": r"\ensuremath{\pm}",
    "≤": r"\ensuremath{\leq}",
    "≥": r"\ensuremath{\geq}",
    "×": r"\ensuremath{\times}",
    "→": r"\ensuremath{\rightarrow}",
    "≈": r"\ensuremath{\approx}",
    "–": "--",
    "…": r"\dots{}",
    "µ": r"\ensuremath{\mu}",
    " ": "~",
}

TEXT_ESCAPES = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "#": r"\#",
    "$": r"\$",
    "%": r"\%",
    "&": r"\&",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}
CODE_ESCAPES = {
    **TEXT_ESCAPES,
    "'": r"\textquotesingle{}",
    '"': r"\textquotedbl{}",
    "`": r"\textasciigrave{}",
}
#: After these characters a line may break inside inline code, which is mostly
#: paths and dotted names that would otherwise run into the margin.
CODE_BREAK_AFTER = frozenset("/._-=@")
#: Backslash escapes CommonMark allows outside code: any ASCII punctuation.
MARKDOWN_ESCAPABLE = frozenset("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~")
#: A straight quote after one of these opens a quotation, after anything else it
#: closes one.
OPENS_QUOTE_AFTER = frozenset(" ([{/\n")


class EdnError(Exception):
    """The notebook cannot be transferred as written; the message says where."""


# --- The notebook ------------------------------------------------------------


@dataclass
class Entry:
    """One `### EDN-NN: title` section of the notebook, with its fields as Markdown."""

    id: str
    number: int
    title: str
    #: The heading's line in reports/edn.md, counted from 1.
    line: int
    #: Markdown of each field, by `FIELD_KEYS` value, the label's line stripped.
    fields: dict[str, list[str]] = field(default_factory=dict)
    #: Fields the template does not define, as (label, Markdown, the field above).
    extra_fields: list[tuple[str, list[str], str]] = field(default_factory=list)
    #: The block quote above the fields, without its `>` markers.
    note: list[str] = field(default_factory=list)
    #: Index into the notebook's lines of the `In LaTeX` field, if it has one.
    in_latex_index: int | None = None
    #: Index of the entry's last non-blank line, where a missing field is added.
    last_index: int = 0

    @property
    def is_reservation(self) -> bool:
        return not self.fields and not self.extra_fields

    @property
    def slug(self) -> str:
        return f"{self.number:02d}-{_slug(self.title)}"


def _slug(title: str, max_words: int = 6) -> str:
    ascii_title = unicodedata.normalize("NFKD", title).encode("ascii", "ignore").decode()
    words = re.findall(r"[a-z0-9]+", ascii_title.lower())
    return "-".join(words[:max_words])


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def _dedent(line: str, line_number: int, entry_id: str) -> str:
    if not line.strip():
        return ""
    if _indent(line) < INDENT:
        raise EdnError(
            f"{entry_id}, reports/edn.md line {line_number}: the line belongs to no field: "
            f"{line.strip()!r}"
        )
    return line[INDENT:]


def parse_notebook(text: str) -> list[Entry]:
    """Parse the `## Entries` section of reports/edn.md into its entries."""
    lines = text.splitlines()
    try:
        start = lines.index(ENTRIES_HEADING) + 1
    except ValueError as error:
        raise EdnError(f"reports/edn.md has no {ENTRIES_HEADING!r} section") from error

    entries: list[Entry] = []
    current: Entry | None = None
    open_field: list[str] | None = None
    for index in range(start, len(lines)):
        line = lines[index]
        if line.startswith("## "):
            _check_no_entry_after(lines, index)
            break
        if line.lstrip().startswith(FENCES):
            where = f"{current.id}, " if current else ""
            raise EdnError(
                f"{where}reports/edn.md line {index + 1}: a fenced code block cannot be "
                "transferred; write the code inline, one span per line"
            )
        heading = ENTRY_HEADING.match(line)
        if heading:
            current = Entry(
                id=heading[1], number=int(heading[2]), title=heading[3], line=index + 1
            )
            current.last_index = index
            entries.append(current)
            open_field = None
            continue
        if current is None or not line.strip():
            if current is not None and open_field is not None:
                open_field.append("")
            continue
        current.last_index = index
        open_field = _parse_line(current, line, index, open_field)

    _check_ids(entries)
    for entry in entries:
        for key, body in entry.fields.items():
            entry.fields[key] = _trim(body)
        if not entry.is_reservation:
            missing = [key for key in REQUIRED_FIELDS if not _is_given(entry.fields.get(key))]
            if missing:
                raise EdnError(
                    f"{entry.id} (reports/edn.md line {entry.line}) is missing the required "
                    f"field(s) {', '.join(missing)}"
                )
    return entries


def _check_no_entry_after(lines: list[str], index: int) -> None:
    """Refuse a `## ` heading that would end the Entries section early.

    The section ends at the next `## ` heading, which is the template's. One
    added between two entries would end it there instead and silently drop every
    entry below it, so an entry heading after it, outside a code block such as
    the template's, is an error.
    """
    in_fence = False
    for later in range(index + 1, len(lines)):
        if lines[later].lstrip().startswith(FENCES):
            in_fence = not in_fence
            continue
        heading = None if in_fence else ENTRY_HEADING.match(lines[later])
        if heading:
            raise EdnError(
                f"reports/edn.md line {index + 1}: the heading {lines[index]!r} ends the "
                f"{ENTRIES_HEADING!r} section, so {heading[1]} on line {later + 1} would be "
                "dropped; entries take `### ` headings and nothing else"
            )


def _parse_line(entry: Entry, line: str, index: int, open_field: list[str] | None):
    """Add one non-blank line to `entry`; return the field that is open after it."""
    if line.startswith(">") and not entry.fields and not entry.extra_fields:
        entry.note.append(line[1:].removeprefix(" "))
        return None
    match = FIELD_LINE.match(line)
    if match:
        label, rest = match["label"], match["rest"] or ""
        body = [rest] if rest else []
        key = FIELD_KEYS.get(label)
        if key is None:
            if not entry.fields:
                raise EdnError(
                    f"{entry.id}, reports/edn.md line {index + 1}: the field {label!r} comes "
                    "before any field of the template, so there is no field to attach it to"
                )
            above = next(reversed(entry.fields))
            entry.extra_fields.append((label, body, above))
            return body
        if key in entry.fields:
            raise EdnError(f"{entry.id}, reports/edn.md line {index + 1}: {label!r} appears twice")
        entry.fields[key] = body
        if key == "in_latex":
            entry.in_latex_index = index
        return body
    if open_field is None:
        raise EdnError(
            f"{entry.id}, reports/edn.md line {index + 1}: the line belongs to no field: "
            f"{line.strip()!r}"
        )
    open_field.append(_dedent(line, index + 1, entry.id))
    return open_field


def _check_ids(entries: list[Entry]) -> None:
    seen: set[str] = set()
    for entry in entries:
        if entry.id in seen:
            raise EdnError(f"{entry.id} has two entries in reports/edn.md")
        seen.add(entry.id)


def _trim(lines: list[str]) -> list[str]:
    while lines and not lines[-1].strip():
        lines = lines[:-1]
    return lines


def _is_given(body: list[str] | None) -> bool:
    """Whether a field says something: not absent, not empty, not the template's "-"."""
    return bool(body) and "\n".join(body).strip() not in ("", "-")


# --- Markdown blocks ---------------------------------------------------------


@dataclass
class Paragraph:
    lines: list[str]


@dataclass
class BulletList:
    items: list[list["Block"]]


@dataclass
class Table:
    header: list[str]
    rows: list[list[str]]


@dataclass
class Quote:
    blocks: list["Block"]


Block = Paragraph | BulletList | Table | Quote


def _is_bullet(line: str) -> bool:
    return line.startswith(("- ", "* "))


def _starts_block(line: str) -> bool:
    return _is_bullet(line) or line.startswith(("|", ">"))


def parse_blocks(lines: list[str]) -> list[Block]:
    """Parse dedented Markdown into blocks; nesting is by two-space indentation."""
    blocks: list[Block] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip():
            index += 1
        elif _is_bullet(line):
            index = _parse_list(lines, index, blocks)
        elif line.startswith("|"):
            end = index
            while end < len(lines) and lines[end].startswith("|"):
                end += 1
            blocks.append(_parse_table(lines[index:end]))
            index = end
        elif line.startswith(">"):
            end = index
            while end < len(lines) and lines[end].startswith(">"):
                end += 1
            quoted = [quoted_line[1:].removeprefix(" ") for quoted_line in lines[index:end]]
            blocks.append(Quote(parse_blocks(quoted)))
            index = end
        else:
            end = index
            while end < len(lines) and lines[end].strip() and not _starts_block(lines[end]):
                end += 1
            blocks.append(Paragraph([text.strip() for text in lines[index:end]]))
            index = end
    return blocks


def _parse_list(lines: list[str], index: int, blocks: list[Block]) -> int:
    items: list[list[Block]] = []
    while index < len(lines) and _is_bullet(lines[index]):
        item = [lines[index][2:]]
        index += 1
        while index < len(lines):
            if lines[index].strip():
                if _indent(lines[index]) < INDENT:
                    break
                item.append(lines[index][INDENT:])
                index += 1
                continue
            # A blank line continues the item only if the item goes on after it.
            after = index
            while after < len(lines) and not lines[after].strip():
                after += 1
            if after == len(lines) or _indent(lines[after]) < INDENT:
                break
            item.extend([""] * (after - index))
            index = after
        items.append(parse_blocks(item))
    blocks.append(BulletList(items))
    return index


def _split_row(row: str) -> list[str]:
    """Split a pipe-table row into cells, ignoring pipes in code and escaped pipes."""
    cells, current, in_code = [], [], False
    body = row.strip().removeprefix("|").removesuffix("|")
    index = 0
    while index < len(body):
        char = body[index]
        if char == "\\" and index + 1 < len(body) and body[index + 1] == "|":
            current.append("|")
            index += 2
            continue
        if char == "`":
            in_code = not in_code
        if char == "|" and not in_code:
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(char)
        index += 1
    cells.append("".join(current).strip())
    return cells


def _parse_table(rows: list[str]) -> Table:
    if len(rows) < TABLE_MIN_ROWS or not re.fullmatch(
        r"\|?\s*:?-+:?\s*(\|\s*:?-+:?\s*)*\|?", rows[1].strip()
    ):
        raise EdnError(f"a table needs a header row and a delimiter row: {rows[0]!r}")
    header = _split_row(rows[0])
    body = [_split_row(row) for row in rows[2:]]
    for cells in body:
        if len(cells) != len(header):
            raise EdnError(f"a table row has {len(cells)} cells, its header {len(header)}")
    return Table(header, body)


# --- Rendering ---------------------------------------------------------------


@dataclass(frozen=True)
class Context:
    """What rendering needs to know beyond the text itself."""

    #: The entries the PDF holds, so a link to one of them can stay inside it.
    known_ids: frozenset[str]
    #: Which entry is being rendered, for error messages.
    entry_id: str = ""


def _check_characters(text: str, context: Context) -> None:
    for char in text:
        if ord(char) < ASCII_END or char in UNICODE_TO_LATEX:
            continue
        if ord(char) < LATIN1_END and unicodedata.category(char).startswith("L"):
            continue
        raise EdnError(
            f"{context.entry_id}: pdfLaTeX cannot typeset {char!r} "
            f"(U+{ord(char):04X}); add it to UNICODE_TO_LATEX in tools/edn_latex.py"
        )


def escape_text(text: str, previous: str = "\n") -> str:
    """Escape prose for LaTeX, with typographic quotes, dashes and percent signs.

    `previous` is the character of the source just before `text`, which decides
    whether a straight quote at its start opens or closes a quotation.
    """
    out: list[str] = []
    for char in text:
        if char in TEXT_ESCAPES:
            out.append(TEXT_ESCAPES[char])
        elif char == '"':
            out.append("``" if previous in OPENS_QUOTE_AFTER else "''")
        elif char == "'" and previous in OPENS_QUOTE_AFTER:
            out.append("`")
        else:
            out.append(UNICODE_TO_LATEX.get(char, char))
        previous = char
    escaped = "".join(out)
    # The notebook writes a plain hyphen between spaces where print uses a dash.
    escaped = escaped.replace(" - ", " -- ")
    # A number and its percent sign stay on one line, with a thin space.
    return re.sub(r"(\d) \\%", r"\1\\,\\%", escaped)


def render_code(code: str) -> str:
    out = []
    for char in code:
        out.append(CODE_ESCAPES.get(char, UNICODE_TO_LATEX.get(char, char)))
        if char in CODE_BREAK_AFTER:
            out.append(r"\allowbreak{}")
    return r"\texttt{" + "".join(out) + "}"


def _resolve_url(target: str) -> str:
    """Turn a link target of reports/edn.md into an absolute URL."""
    if re.match(r"^[a-z]+:", target):
        return target
    path, _, anchor = target.partition("#")
    resolved = posixpath.normpath(posixpath.join(EDN_MD_REPO_DIR, path)) if path else ""
    if resolved.startswith(".."):
        raise EdnError(f"the link {target!r} points outside the repository")
    # A bare `#anchor` that is not an entry points into the notebook itself.
    url = f"{REPO_URL}/blob/main/{resolved or EDN_MD_REPO_DIR + '/edn.md'}"
    return f"{url}#{anchor}" if anchor else url


def _href(url: str, label: str, context: Context) -> str:
    if not URL_SAFE.match(url):
        raise EdnError(f"{context.entry_id}: the URL {url!r} has a character \\href cannot take")
    # `\href` reads its URL verbatim only when it is not inside another macro's
    # argument, and every value of `\ednentry` is. `#`, `%` and `&` therefore take
    # a backslash, which hyperref removes again; a tilde would be an active
    # character, so it is percent-encoded, which is the same URL.
    escaped = url.replace("~", "%7E").replace("%", r"\%").replace("#", r"\#").replace("&", r"\&")
    return rf"\href{{{escaped}}}{{{label}}}"


def _render_link(label_md: str, target: str, context: Context) -> str:
    label = render_inline(label_md, context)
    anchor = EDN_ANCHOR.match(target)
    if anchor:
        entry_id = f"EDN-{int(anchor[1]):02d}"
        # A link to an entry this PDF does not hold would be a dead link; the
        # label already names the entry, so it stays as text.
        return rf"\hyperref[{entry_id}]{{{label}}}" if entry_id in context.known_ids else label
    return _href(_resolve_url(target), label, context)


def _find_closing(text: str, start: int, opening: str, closing: str) -> int:
    """Index of the bracket that closes the one at `start`, skipping code spans."""
    depth, index = 0, start
    while index < len(text):
        char = text[index]
        if char == "`":
            end = text.find("`", index + 1)
            index = end + 1 if end != -1 else index + 1
            continue
        if char == "\\":
            index += 2
            continue
        if char == opening:
            depth += 1
        elif char == closing:
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return -1


def _match_link(text: str, start: int) -> tuple[str, str, int] | None:
    label_end = _find_closing(text, start, "[", "]")
    if label_end == -1 or not text.startswith("(", label_end + 1):
        return None
    target_end = _find_closing(text, label_end + 1, "(", ")")
    if target_end == -1:
        return None
    return text[start + 1 : label_end], text[label_end + 2 : target_end].strip(), target_end + 1


def _match_emphasis(text: str, start: int) -> tuple[str, str, int] | None:
    """Match `**bold**` or `*italic*` at `start`, as (command, inner text, end)."""
    if text.startswith("**", start):
        end = text.find("**", start + 2)
        if end > start + 2:
            return "textbf", text[start + 2 : end], end + 2
        return None
    if start + 1 < len(text) and text[start + 1] not in " *":
        end = start + 1
        while True:
            end = text.find("*", end)
            if end == -1:
                return None
            if text[end - 1] != " " and not text.startswith("**", end):
                return "emph", text[start + 1 : end], end + 1
            end += 1
    return None


def render_inline(text: str, context: Context) -> str:
    """Render one paragraph's worth of inline Markdown as LaTeX."""
    _check_characters(text, context)
    out: list[str] = []
    plain: list[str] = []
    # The source character before the pending plain text, for `escape_text`.
    before_plain = "\n"

    def flush() -> None:
        out.append(escape_text("".join(plain), before_plain))
        plain.clear()

    index = 0
    while index < len(text):
        char = text[index]
        token = _match_token(text, index, char, context)
        if token is None:
            if not plain:
                before_plain = text[index - 1] if index else "\n"
            if char == "\\" and index + 1 < len(text) and text[index + 1] in MARKDOWN_ESCAPABLE:
                plain.append(text[index + 1])
                index += 2
            else:
                plain.append(char)
                index += 1
            continue
        rendered, index = token
        flush()
        out.append(rendered)
    flush()
    return "".join(out)


def _match_token(text: str, index: int, char: str, context: Context) -> tuple[str, int] | None:
    """Render the code span, link, autolink or emphasis starting at `index`, if any."""
    if char == "`":
        run = len(text[index:]) - len(text[index:].lstrip("`"))
        fence = "`" * run
        end = text.find(fence, index + run)
        if end == -1:
            return None
        code = text[index + run : end]
        if code.startswith(" ") and code.endswith(" ") and code.strip():
            code = code[1:-1]
        return render_code(code), end + run
    if char == "[":
        link = _match_link(text, index)
        if link:
            label, target, end = link
            return _render_link(label, target, context), end
    if char == "<":
        autolink = AUTOLINK.match(text, index)
        if autolink:
            url = autolink[1]
            return _href(url, render_code(url), context), autolink.end()
    if char == "*":
        emphasis = _match_emphasis(text, index)
        if emphasis:
            command, inner, end = emphasis
            return rf"\{command}{{{render_inline(inner, context)}}}", end
    return None


def _render_paragraph(paragraph: Paragraph, context: Context) -> str:
    # Lines are joined with a space, as Markdown does, except that each "Pros:"
    # and "Cons:" of an alternative starts its own line, which is how the notebook
    # lays them out and what makes a list of alternatives readable in print.
    rendered = []
    for number, line in enumerate(paragraph.lines):
        text = render_inline(line, context)
        if number and line.startswith(("Pros:", "Cons:")):
            rendered.append(r"\newline " + text)
        else:
            rendered.append(text)
    return "\n".join(rendered)


def _render_table(table: Table, context: Context) -> str:
    columns = r">{\raggedright\arraybackslash}X" * len(table.header)
    lines = [
        # A little air between rows, which mostly wrap onto several lines here.
        r"{\small\renewcommand{\arraystretch}{1.15}%",
        r"\begin{tabularx}{\linewidth}{@{}" + columns + "@{}}",
        r"\toprule",
        " & ".join(render_inline(cell, context) for cell in table.header) + r" \\",
        r"\midrule",
    ]
    lines += [
        " & ".join(render_inline(cell, context) for cell in row) + r" \\" for row in table.rows
    ]
    lines += [r"\bottomrule", r"\end{tabularx}}"]
    return "\n".join(lines)


def render_blocks(blocks: list[Block], context: Context) -> str:
    rendered = []
    for block in blocks:
        if isinstance(block, Paragraph):
            rendered.append(_render_paragraph(block, context))
        elif isinstance(block, BulletList):
            items = "\n".join(r"\item " + render_blocks(item, context) for item in block.items)
            rendered.append(
                "\\begin{itemize}[leftmargin=*, topsep=2pt]\n" + items + "\n\\end{itemize}"
            )
        elif isinstance(block, Table):
            rendered.append(_render_table(block, context))
        else:
            rendered.append(r"{\itshape " + render_blocks(block.blocks, context) + "}")
    return "\n\\par\n".join(rendered)


def render_markdown(lines: list[str], context: Context) -> str:
    return render_blocks(parse_blocks(lines), context)


def _render_title(title: str, context: Context) -> str:
    # The title also becomes a PDF bookmark, which cannot hold \texttt, so each
    # code span carries a plain-text form for the bookmark.
    parts = re.split(r"(`[^`]+`)", title)
    rendered = []
    for part in parts:
        if part.startswith("`") and part.endswith("`") and len(part) > 1:
            plain = escape_text(part[1:-1])
            rendered.append(rf"\texorpdfstring{{{render_code(part[1:-1])}}}{{{plain}}}")
        else:
            rendered.append(render_inline(part, context))
    return "".join(rendered)


def render_entry(entry: Entry, known_ids: frozenset[str]) -> str:
    """The `\\ednentry{...}` file for one entry, header included."""
    try:
        return _render_entry(entry, known_ids)
    except EdnError as error:
        # Some checks know the entry and some, deep in a table or a link, do not;
        # either way the message names it once.
        if str(error).startswith(f"{entry.id}:"):
            raise
        raise EdnError(f"{entry.id}: {error}") from error


def _render_entry(entry: Entry, known_ids: frozenset[str]) -> str:
    context = Context(known_ids=known_ids, entry_id=entry.id)
    values: dict[str, str] = {"id": entry.id, "title": _render_title(entry.title, context)}
    if entry.note:
        values["note"] = render_markdown(entry.note, context)
    for key, body in entry.fields.items():
        if key in ("alternatives", "rationale", "in_latex") or not _is_given(body):
            continue
        values[key] = render_markdown(body, context)

    # Fields the template does not define go below the field they follow.
    for label, body, above in entry.extra_fields:
        # The alternatives are rendered into the rationale and `In LaTeX` is not
        # rendered at all, so what follows either goes to the next printed field.
        target = {"alternatives": "rationale", "in_latex": "evidence"}.get(above, above)
        addition = rf"\textbf{{{escape_text(label)}:}} " + render_markdown(body, context)
        values[target] = (values[target] + "\n\\par\n" if target in values else "") + addition

    rationale = []
    if _is_given(entry.fields.get("alternatives")):
        rationale.append(
            r"\emph{Alternatives considered:}"
            + "\n"
            + render_markdown(entry.fields["alternatives"], context)
        )
        rationale.append(r"\emph{Why:} " + render_markdown(entry.fields["rationale"], context))
    else:
        rationale.append(render_markdown(entry.fields["rationale"], context))
    if "rationale" in values:  # an extra field that followed the rationale
        rationale.append(values["rationale"])
    values["rationale"] = "\n\\par\n".join(rationale)

    lines = [GENERATED_MARKER, DO_NOT_EDIT, r"\ednentry{"]
    for key in OUTPUT_KEYS:
        if key in values:
            lines.append(f"  {key} = {{{values[key]}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"


# --- The transfer ------------------------------------------------------------


@dataclass
class TransferResult:
    transferred: list[str]
    skipped: list[str]
    written: list[Path]
    removed: list[Path]
    notebook_changed: bool


def _set_in_latex(lines: list[str], entries: list[Entry]) -> list[str]:
    """The notebook's lines with `In LaTeX: yes` on every given entry."""
    updated = list(lines)
    # From the bottom up, so an inserted line does not move the ones still to do.
    for entry in sorted(entries, key=lambda item: item.last_index, reverse=True):
        field_line = f"- **{IN_LATEX_LABEL}:** yes"
        if entry.in_latex_index is not None:
            updated[entry.in_latex_index] = field_line
        else:
            updated.insert(entry.last_index + 1, field_line)
    return updated


@dataclass
class Plan:
    """What the LaTeX EDN and the notebook should hold, computed without writing."""

    entries: list[Entry]
    #: Every generated file, by name inside the LaTeX directory, with its content.
    files: dict[str, str]
    #: The notebook as it should read, with `In LaTeX: yes` on every entry.
    notebook: str

    @property
    def transferred(self) -> list[str]:
        return [entry.id for entry in self.entries if not entry.is_reservation]

    @property
    def skipped(self) -> list[str]:
        return [entry.id for entry in self.entries if entry.is_reservation]


def plan(text: str) -> Plan:
    """Render the notebook `text` into the files and the notebook a transfer leaves."""
    entries = parse_notebook(text)
    written_entries = [entry for entry in entries if not entry.is_reservation]
    known_ids = frozenset(entry.id for entry in written_entries)

    files = {f"{entry.slug}.tex": render_entry(entry, known_ids) for entry in written_entries}
    entry_list = "\n".join(
        [
            GENERATED_MARKER,
            DO_NOT_EDIT,
            "% One \\input per entry, oldest first.",
            *(rf"\input{{edn/{entry.slug}}}" for entry in written_entries),
        ]
    )
    files[ENTRY_LIST_NAME] = entry_list + "\n"

    lines = text.splitlines()
    updated = _set_in_latex(lines, written_entries)
    if updated == lines:
        notebook = text
    else:
        notebook = "\n".join(updated) + ("\n" if text.endswith("\n") else "")
    return Plan(entries=entries, files=files, notebook=notebook)


def _is_generated(path: Path) -> bool:
    with path.open(encoding="utf-8") as handle:
        return handle.readline().rstrip("\n") == GENERATED_MARKER


def _differences(
    edn_md: Path, latex_dir: Path, target: Plan
) -> tuple[list[Path], list[Path], bool]:
    """The files a transfer would write and remove, and whether it would edit the notebook."""
    to_write = [
        latex_dir / name
        for name, content in target.files.items()
        if not (latex_dir / name).exists()
        or (latex_dir / name).read_text(encoding="utf-8") != content
    ]
    existing = sorted(latex_dir.glob("*.tex")) if latex_dir.is_dir() else []
    to_remove = [
        path for path in existing if path.name not in target.files and _is_generated(path)
    ]
    notebook_changes = edn_md.read_text(encoding="utf-8") != target.notebook
    return to_write, to_remove, notebook_changes


def transfer(edn_md: Path = EDN_MD, latex_dir: Path = LATEX_EDN_DIR) -> TransferResult:
    """Transfer every written entry of `edn_md` into `latex_dir`."""
    target = plan(edn_md.read_text(encoding="utf-8"))
    to_write, to_remove, notebook_changes = _differences(edn_md, latex_dir, target)

    latex_dir.mkdir(parents=True, exist_ok=True)
    for path in to_write:
        path.write_text(target.files[path.name], encoding="utf-8")
    for path in to_remove:
        path.unlink()
    if notebook_changes:
        edn_md.write_text(target.notebook, encoding="utf-8")

    return TransferResult(
        transferred=target.transferred,
        skipped=target.skipped,
        written=to_write,
        removed=to_remove,
        notebook_changed=notebook_changes,
    )


def check(edn_md: Path = EDN_MD, latex_dir: Path = LATEX_EDN_DIR) -> list[str]:
    """What a transfer would change, as one line per file; empty when in sync."""
    target = plan(edn_md.read_text(encoding="utf-8"))
    to_write, to_remove, notebook_changes = _differences(edn_md, latex_dir, target)
    stale = [f"{path.name} would be written" for path in to_write]
    stale += [f"{path.name} would be removed" for path in to_remove]
    if notebook_changes:
        stale.append(f"{edn_md.name} would get In LaTeX: yes on an entry")
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--edn-md", type=Path, default=EDN_MD)
    parser.add_argument("--latex-dir", type=Path, default=LATEX_EDN_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="change nothing, and exit 1 when the LaTeX EDN is behind reports/edn.md",
    )
    args = parser.parse_args(argv)
    try:
        if args.check:
            stale = check(args.edn_md, args.latex_dir)
            if stale:
                print("The LaTeX EDN is behind reports/edn.md; run `make edn` and commit:")
                for line in stale:
                    print(f"  {line}")
                return 1
            print("The LaTeX EDN is in sync with reports/edn.md.")
            return 0
        result = transfer(args.edn_md, args.latex_dir)
    except EdnError as error:
        # Printed rather than raised: the message names the entry and the line,
        # which is all there is to fix, and a traceback would bury it.
        print(f"error: {error}", file=sys.stderr)
        return 1
    for entry_id in result.skipped:
        print(f"{entry_id} has a heading and no fields yet, so it is not transferred.")
    for path in result.removed:
        print(f"Removed {path.name}, which no entry produces any more.")
    print(
        f"{len(result.transferred)} entries transferred, {len(result.written)} file(s) written, "
        f"{len(result.removed)} removed; reports/edn.md "
        f"{'updated' if result.notebook_changed else 'unchanged'}."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
